name: Deploy Astro to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: withastro/action@v2
        with:
          path: ./
          site: https://yongmanpark.github.io/dk-test/
          deploy: true
